### ISSUE TITLE
テキストスタイルの調整

### ISSUE THREAD

**Issue by yurimatumoto** [matumotoyuri/myportfolio#16]
wider768px
h1 {
    margin-bottom: 0 0 20px;
    font-size: 2.3rem;
    line-height: 28px;
    letter-spacing: 1.3;
    font-weight: bold;
}
body {
    margin: 0 auto;
    color: #3B3D40;
    font-size: 15px;
    font-family: "Noto Sans JP";
    letter-spacing: 0.1em;
    line-height: 24px;
}
.a-blue {
    color: #2E71F2;
    text-decoration: none;
    font-size: 0.9rem;
}

**Comment by yurimatumoto** [comment]
less768px
h1 {
margin-bottom: 0 0 20px;
font-size: 2.3rem;
line-height: 28px;
letter-spacing: 1.3;
font-weight: bold;
}
body {
    margin: 0 auto;
    color: #3B3D40;
    font-size: 15px;
    font-family: "Noto Sans JP";
    letter-spacing: 0.1em;
    line-height: 24px;
}
.a-blue {
color: #2E71F2;
text-decoration: none;
font-size: 0.9rem;
}

**Comment by 567000** [comment]
対応！
確認してOKそうならCloseしてください

**Comment by yurimatumoto** [comment]
ごめんなんだよh1とリンクも変えてみたんだよ
webサイズだと16pxの文字のboldはそんなに太い印象にならないんだね
