### ISSUE TITLE
レスポンシブデザインに合わせた画像サイズ、モジュールサイズにするぞ

### ISSUE THREAD

**Issue by yurimatumoto** [matumotoyuri/myportfolio#28]
https://projects.invisionapp.com/d/main#/projects/prototypes/16506107
Grid systemのスケッチに記入
レスポンシブデザインになるようモジュールのサイズと設定がされているぞ。

index lab(3サイズ)ブレイクポイント960 768 480
work 960 768

**Comment by 567000** [comment]
対応しましたが、諸々の事情でブレイクポイントは以下になってますがいいですか？
1200px  992px  768px  544px

**Comment by yurimatumoto** [comment]
ブレイクポイント上記の
1200px 992px 768px 544px
で合わせて考えて行ったほうがいいってことかな

**Comment by yurimatumoto** [comment]
多分出来た！
