### ISSUE TITLE
画面サイズ変更でロゴが同じマージンを左に持つようにする

### ISSUE THREAD

**Issue by yurimatumoto** [matumotoyuri/myportfolio#34]
<img width="1232" alt="スクリーンショット 2019-05-20 20 05 53" src="https://user-images.githubusercontent.com/17585116/58017310-d6963a80-7b3a-11e9-9e93-32803a45888b.png">
<img width="1272" alt="スクリーンショット 2019-05-20 20 05 48" src="https://user-images.githubusercontent.com/17585116/58017312-d6963a80-7b3a-11e9-8dbb-62549941ae6f.png">
とあるサイズでなぜかひ左にくっつく

**Comment by 567000** [comment]
調整してみました
ご確認を

**Comment by yurimatumoto** [comment]
できてたです！ありがとうです。
