### ISSUE TITLE
INDEX以外のworkの動画をvimeoのiframeにしたい

### ISSUE THREAD

**Issue by yurimatumoto** [matumotoyuri/myportfolio#36]

**Comment by yurimatumoto** [comment]
タカマガハラの動画が重すぎてダメだ

**Comment by yurimatumoto** [comment]
onakapoyopoyo https://vimeo.com/226128559
takamagahara https://vimeo.com/316937925
SAND FACE https://vimeo.com/337932245
vimeoのリンクです

**Comment by 567000** [comment]
しましたー
iPhoneでどう見えるか確認おねがいします

**Comment by yurimatumoto** [comment]
再生できてたありがとうー
ただ横画面でも再生できたいので
優先じゃ無いですが別件で残します。。。。
