### ISSUE TITLE
Aboutの紹介文と構成を変えたので適用

### ISSUE THREAD

**Issue by yurimatumoto** [matumotoyuri/myportfolio#7]
紹介文の構成を変えました。
web版、SP版文言修正。構成変更です。

**Comment by yurimatumoto** [comment]
紹介文とグラフィックの職業も変えました。
Aboutoのページは全て変わったと思ってもらって大丈夫です。

**Comment by 567000** [comment]
更新しました！こんな感じでどうでしょう？？
https://matumotoyuri.com/about/

**Comment by yurimatumoto** [comment]
ありがとうなんだよ。
web
Careerの2009などのフォントを太文字
Interestの行間が広いのでAboutと合わせて欲しいんだよ
スマホ
Aboutトップの画像を変えて欲しいんだよ
https://projects.invisionapp.com/d/main#/projects/prototypes/16506107/assets/275281653
